# Generated by Django 3.1.7 on 2021-03-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decision_tree_classifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisiontreeinput',
            name='to_be_predicted',
        ),
    ]
