# Generated by Django 3.1.7 on 2021-03-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_tree_classifier', '0002_remove_decisiontreeinput_to_be_predicted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionTreeTestDataInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_tree_json', models.JSONField()),
                ('test_data_file', models.FileField(upload_to='')),
            ],
        ),
    ]
