# Generated by Django 3.1.7 on 2021-03-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_tree_classifier', '0003_decisiontreetestdatainput'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisiontreeinput',
            name='target_feature',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
